# Generated by Django 4.2.1 on 2023-07-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0006_remove_coursecontent_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='file',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='content',
            field=models.FileField(blank=True, upload_to='templates/'),
        ),
    ]
