# Generated by Django 4.2.1 on 2023-07-21 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0010_payment_delete_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_price',
        ),
    ]
