# Generated by Django 4.2.1 on 2023-07-21 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0011_remove_payment_payment_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='purchased_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
