# Generated by Django 4.2.1 on 2023-07-14 12:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Instructor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coursera.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=200)),
                ('body', models.TextField()),
                ('content', models.TextField()),
                ('video', models.FileField(upload_to='course_videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='coursera.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursera.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursera.coursecontent'),
        ),
    ]
