# Generated by Django 4.2.1 on 2023-07-16 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0003_coursecontent_course_remove_course_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='video',
        ),
    ]
