# Generated by Django 4.2.1 on 2023-07-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0007_remove_coursecontent_file_coursecontent_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecontent',
            name='content',
        ),
        migrations.AddField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
