# Generated by Django 4.2.1 on 2023-07-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursera', '0008_remove_coursecontent_content_purchase_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
    ]
